from enum import Enum

class MessageType(Enum):
    NONE = 0
    FEEDBACK = 1
    NO_CONNECTION = 2
    OPTIMIZATION_NOT_RUNNING = 3
    OPTIMIZATION_STILL_RUNNING = 4
    OPTIMIZATION_SUCCESS = 5
    OPTIMIZATION_FAIL = 6
    OPTIMIZATION_CANCELLED_BY_USER = 7
    REGISTRATION_FAILED = 8
    SELECT_DEFINITION_DIALOG = 9
    FORCE_DEFINITION_DIALOG = 10
    SAVED_OBJECT_DIALOG = 11
    MESH_ANALYSIS_RUNNING = 12
    SCENE_NOT_READY = 13
    LIMIT_EXCEEDED = 14
    REGISTRATION_SENT = 15
    LOG_IN_OUT_MESSAGE = 16
    TOO_MANY_REQUESTS = 17
    UPDATE_EXTRUDER_SETTINGS_REQUEST=18
    LOG_IN_ERROR=19
    PREVIOUS_STEP_NOT_CONFIRMED=20
    MISSING_USER_ACTION=21
    OPEN_SAMPLES=22
    SAMPLE_SETUP=23
    UNKNOWN = 99